name: SpeckAndTech
title: Speck&Tech

description: ""

url: https://speckand.tech
permalink: "/:year/:month/:title/"

port: 4268
destination: _site
assets_dir: _assets
# data_dir: _data
# drafts_dir: _drafts
# posts_dir: _posts
# layouts_dir: _templates/layouts
# includes_dir: _templates/includes
# collections_dir: _pages
collections:
  job_offers:
    output: true
    permalink: "/:collection/:title/"
    sort_by: title

encoding: UTF-8

sass:
  sass_dir: _assets/css
  style: compressed
  sourcemap: never

plugins: []

keep_files: []

include: ["_assets"]
exclude: ["_assets/css/bootstrap"]

# Variables
RETREAT_EDITION: 4
